server:
  ip: 127.0.0.1
  port: 10010
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/helper-dev?useUnicode=true&autoReconnect=true&allowMultiQueries=true&characterEncoding=utf-8&connectTimeout=1000&socketTimeout=180000&useSSL=false
    username: root
    password: admin123
